### ISSUE TITLE
ELS functional logic appeared to work...display flickered for a while, now dead

### ISSUE THREAD

**Issue by TreatHull** [clough42/electronic-leadscrew#113]
When first hooked up, the control panel was DOA - no sign of life in any regard.

After tracing, tracing and tracing again, I found that the ground wasn't connecting with the control panel. When I tested the cable (an old VGA cable), the ground lead was open. 

After several efforts to troubleshoot, I got to a place where when I powered up the unit, one red LED illuminated on the control board....but nothing else happened.

I carefully made up a new cable to connect the control panel only 12" long to minimize noise and when I powered up - the control panel was sort of working. The alpha-numeric display was seemed very dim and flickering quickly, but I could make out Clough42 and the version number. 

After the bootup information was done, the RPM showed zero unless I spun the encorder, when it produced plausible RPM just like it was supposed to, except so dim and flickering it was almost impossible to see.

Likewise, when I pressed the up and down buttons for feed, the value in the feed screen went up and down like it was supposed to. However it was also so dim and flickering that it was almost impossible to see.

While this was going on, several of the red LEDs at the top of the control panel were lit up. LED's 1 and 2 were brightly lit, while LEDs 4 and 7 were lit but not as brightly. (See image below. The numerals look quite bright in this image, but they are actually fickering on and off very quickly making them appear dim.) ![ELS Flickering](https://user-images.githubusercontent.com/66688852/100484478-99fdb480-30ca-11eb-8ce3-9a84e09003f9.jpeg)

I broke out my 100MHz Rigol dual channel oscilliscope, but had to do some reading (and watching youtube videos) to try to understand how  the control panel worked and what stb, clk and dio were supposed to be doing.

When I fired things up again with the scope attached to stb and clk, it didn't look right (see screen images below with blue trace = stb and yellow trace = clk). If I understand correctly, it's sort of working correctly: when stb goes low, the clk turns on.

![Waveform 1](https://user-images.githubusercontent.com/66688852/101107220-d7b57e00-359f-11eb-97ed-6a60aa8ff43d.png)
![Waveform 2](https://user-images.githubusercontent.com/66688852/101107221-d84e1480-359f-11eb-8d6b-bcc2c9fe4bce.png)
![Waveform 3](https://user-images.githubusercontent.com/66688852/101107222-d84e1480-359f-11eb-9167-d1c710018f7a.png)
![Waveform 4](https://user-images.githubusercontent.com/66688852/101107223-d84e1480-359f-11eb-9087-b960d8923457.png)

However, I expected to find more 'binary' voltage values, either 5 vdc or 0. Instead, there are intermediate voltages that showed up and also what looked like noise.

Update: December 13th, 2020

In order to keep up momentum, I switched my focus from the display to installing all the components in my Hammond steel cabinet (which took a lot longer than I expected). When I powered it up, the servo/hybrid stepper appear to work fine, but now no more digits on the control panel, just a red LED at the left end of the board.

I checked continuity from on end to the other, but everything checked out fine, so I figured the problem has to be at the level of one of the boards. I ordered another TI Launchpad, a Clough42 booster board and an LED & KEY board. While waiting for them to arrive, I figured I could test the existing LED & KEY board by using an Arduino to power it and see if I couldn't get the display to light up.

I tried two different Arduino sketches (programs) to drive the TM 1638 LED & KEY board but ... nada! I double-checked the pinouts for each one and they were fine. The waveforms on my scope looked fine, but there's no way I could make the segments light up. This suggests that the LED & KEY board is at least part of the problem, if not the whole problem. I'll know more once the replacement board gets here sometime in 2021.

Update  December 16th

The new Launchpad arrived from Digi-Key in just over a day. I removed the jumpers, set the switches and wired it in last night. The encoder drove the hybrid stepper correctly but the LED & KEY Board was still dead. 

To try and understand why the board was dead (except for one red LED which showed it had power), I hooked up the oscilliscope again.

Even though the control panel didn’t function, the signals being passed to the control panel were more ‘healthy’ looking.

![STB   CLK waveforms 2020-12-16](https://user-images.githubusercontent.com/66688852/102417738-45af6b80-3fca-11eb-9198-99beb1ceb49f.png)

Channel 1 above shows the STB while Channel 2 shows CLK. As it’s supposed to, when STB goes low, CLK is activated.

The waveforms are a lot closer to what I expected, but I still wound up with some unanswered questions. Let me start with the questions I had on the screen capture above. The vertical scale for both channels is 2.00 volts/division. Examination shows that the delta between high/low for the STB line is closer to 2 volts than the 5 I expected. Does it matter? if so, what could be causing this? Does it matter?

![STB   DIO waveforms2020-12-16](https://user-images.githubusercontent.com/66688852/102417787-68418480-3fca-11eb-93be-439e96104899.png)

In the second image above Channel 1 shows STB while channel 2 shows DIO. When STB goes low, commands or data are sent on DIO.

The y-axis scale for both lines is still 2 volts/division. What caught my attention in the display was the waveform on DIO (blue) where halfway through the wave train, the lower voltage level increased by a volt giving a 4 volt delta between high and low. I had the same question here: does it matter? And if so, what could be causing it.

At the current pace, I may actually learn something by the time the new display board arrives from China in the new year.

Incidentally, in case it helps someone else, I found a YouTube tutorial on the operation of the TM 1638 display which really helped me understand what was going on: [https://youtu.be/KxfhVqne1Qs](https://youtu.be/KxfhVqne1Qs) You can ignore the Arduino code and just focus on the communications protocol for the display if you want to.

I should have the Clough49 booster board delivered next, followed by the new LED & KEY board sometime in January (!). One board down, two to go.

Update December 25th

The Clough42 Booster Board arrived a few days ago. I soldered the required bits and pieces, tested for continuity from the pins on the board to the display (all good) and powered it up. No display, except for the red LED on the board. With two out of three boards replaced and no joy yet, it's highly suggestive that it's the display board. Further testing may have to wait on the arrival of the slow boat from China.

**Comment by stahlous** [comment]
I had similar issues with flickering on my LED & KEY board. I had very reasonable `signal voltages on my oscilloscope with the LED & KEY board disconnected, but they went to heck when I reconnected it. I figured I screwed up the soldering when I removed the straighter header pins to connect the supplied 90deg header pins. Turns out that was the issue -- after I re-soldered all the connections it runs solidly. I figure I probably had a whisker of solder nearly shorting out +5V to GND.

**Comment by TreatHull** [comment]
December 31st update:

Thanks to @stahlous, one problem solved.
 
I went back and examined the solder job I did on the header and I must have been really careless when I de-solder and removed the old header because a bit of the copper via was lifted and torn away from the Vcc pin. Other parts of the board were getting power, but the torn via appears to have cut off the supply voltage to the TM1638. No wonder nothing was happening.

I did a real kludge repair which involved a blob of solder on the end of a piece of #24 wire and then hooked it up to my Arduino, but still nothing happened. 

As I checked the sketch (program) for the Arduino, I finally noticed that the pin assignment for the output pins was wrong in the code I copied online. One minute correcting and uploading the sketch and -bingo- the control panel lit up at full brightness, no flickering and worked the way it was supposed to with the little Arduino test program.

When I switched cables and connected the control panel to the ELS, the control panel was dead once again.

When I hooked up the scope, I found that the STB and CLK waveforms were good, but that the voltage difference from high to low was only about 2.5 volts:

![STB CLK results](https://user-images.githubusercontent.com/66688852/103429882-8e9e1d00-4b91-11eb-93ca-407567ae6c51.png)

However, when I put the scope on STB and DIO, I got a different result. The voltage swing on DIO was just over 5 volts - what you'd expect, while STB was still only about 2.5 volts. 

![STB DIO results](https://user-images.githubusercontent.com/66688852/103430423-ea68a600-4b91-11eb-8417-a40c1a715516.png)

I got the same waveforms with and without the control panel connected.

So now (1) the control panel works correctly with signal input from my Arduino which is progress; and (2) I trying to figure out what would limit the high-low voltage swing on STB and CLK, but not DIO.

**Comment by JonWoellhaf** [comment]
I suggest you carefully check the switch settings and jumper configuration on the TI board. Good luck!

**Comment by forrestlw** [comment]
It appears that he is using a Arduino board. I didn't respond because the Clough42 project it based on a TI board.  "I tried two different Arduino sketches (programs) to drive the TM 1638 LED & KEY board "

**Comment by TreatHull** [comment]
@forrestlw  Sorry if I wasn't clear in my explanation. The ELS uses the same components as James at Clough42: a TI Launchpad, the Clough42 booster board and a TM 1638 control panel from Clough42.  

The Ardunio board was only used to test whether the TM 1638 control panel was functioning correctly, which it was.

**Comment by TreatHull** [comment]
Hurray!! The slow boat from China arrived this week and my new control panel board was delivered.

Connected it up, fired up the system....and it works perfectly.

The problem was a bum control panel board, probably due to my rough-handling the removal of the original header and installing the new one.

Even before I hook it up to the lathe, I want to say that this has been a terrific project. This is a hobby that I pursuit to have fun and learned new things. Though it required some patience, I had fun and I learned buckets, one of the most rewarding projects I've done in long time.  I encourage anyone else who's considering it to give it a go.

Couldn't have done it without the excellent videos and components from Clough42 and the advice received. Spec thanks to @stahlous who hit the nail on the head. Thanks all!!

![ELS New Control Board](https://user-images.githubusercontent.com/66688852/104106746-7317ce00-5285-11eb-96e0-b7cbb622c0d7.jpeg)
