### ISSUE TITLE
Small Typos in the Wiki

### ISSUE THREAD

**Issue by cfra** [clough42/electronic-leadscrew#135]
I discovered two small typos in the wiki and thought I would point those out, as the rest of the documentation seems quite meticulous to me, and opening a pull request is apparently not possible for wiki pages.

They are both on https://github.com/clough42/electronic-leadscrew/wiki/Wiring-Everything-Together

One suggested change would be:

```diff
-The encoder usually five wires, plus a shield
+The encoder usually has five wires, plus a shield
```

And the other one would be:

```diff
-If you're having trouble, try checking the contiunity of your connections.
+If you're having trouble, try checking the continuity of your connections.
```

**Comment by clough42** [comment]
Fixed.  Thanks.
