### ISSUE TITLE
Youtube Part 16 Encoder Coonector to Electronics Enclosure.

### ISSUE THREAD

**Issue by Geoff-McCombe** [clough42/electronic-leadscrew#141]
My encoder only has five wires plus a braided shield and the board header pins also count five.  I am confused as to why the encoder connector is a nine pin connector.

I am sure  I am missing something simple, please help.

Thanks

Geoff

**Comment by JonWoellhaf** [comment]
Are you asking about the nine pin encoder connector on the servo driver?

**Comment by Geoff-McCombe** [comment]
James says it’s 9 pin for spindle encoder, but if that’s for the encoder on the hybrid servo, mine seems to have 15 pins. Or is it something to do with the tool post grinder. I’m sure I’m missing something simple, but I can’t work it out.

**Comment by Geoff-McCombe** [comment]
I'm thinking these are just standard connectors, so I will use 5 pins of the 9 pin connector for the spindel encoder.
