### ISSUE TITLE
STEPPER_RESOLUTION in SanityCheck.h

### ISSUE THREAD

**Issue by sc0pex** [clough42/electronic-leadscrew#17]
why are the max stepper resolution set to 2000?

I run a hybrid stepper servo with a resolution at 1600. and er gear ratio 2:1
so my resolution in software would be 3200.

i just change the setting in the SanityCheck.h file, but could there be some problem in that.?
is the hardware capable to do the math fast fast enough..?

**Comment by clough42** [comment]
I just picked a number.  I'm mostly just trying to catch errors.  You can
always set the microsteps to 2 to cover your gear ratio.

James
