### ISSUE TITLE
How do I add more threads, Bigger ones, MM and Inch. Please help

### ISSUE THREAD

**Issue by johncharles15** [clough42/electronic-leadscrew#189]
Hi all
Can anyone please tell me how to add more threads, especially lager ones. eg. 6 and 4tpi

**Comment by clough42** [comment]
Take a look at Tables.cpp.  It contains the four tables of threads and feeds.

Each entry in the table has the text characters to display, and the actual ratio, expressed in TPI x 10 or MM x 100.
