### ISSUE TITLE
Best of both float and int calculatons

### ISSUE THREAD

**Issue by choelzen** [clough42/electronic-leadscrew#2]
Here is a simple, fast way to keep the loop timing loop short using the hardware floating point AND eliminate the round off errors created as the count runs for a longer time.  By periodically computing an error difference in the result from the floating point and numerator/divisor integer calculations: Then adding this error in the floating point interrupt code.
  
In core.h
#ifdef USE_FLOATING_POINT
//******************* add an error adjustment calculated in extra cycles using Int ******************
    return ((float)count) * this->feed * feedDirection + error;
****************
Then in extra cycles in the main loop (outside the interrupts)
count_grab=count; //make a copy of the  volatile counter constantly being changed by hardware
error = ((long long)count_grab) * feed->numerator / feed->denominator * feedDirection 
           - ((float)count_grab) * this->feed * feedDirection  ;

//make sure int error=0 at startup

The error will change rather slowly and can be updated every few seconds.  By adding the calculated error in the floating point loop the microstep error can be reduced to 1.

**Comment by clough42** [comment]
I'm going to leave this open for now.  This increases complexity and the opportunity for errors--especially race conditions between the slow loop and the fast interrupt handler.

I don't want to make things harder until after the system has been proven on a real machine, just to reduce cognitive load while debugging other issues.

Will reconsider once things are a little more mature.
