### ISSUE TITLE
Encoder Type

### ISSUE THREAD

**Issue by KennethLuscombe** [clough42/electronic-leadscrew#200]
Can i use a 600p5-26v encoder instead of the 1024p - if so what settings do i need to use.

**Comment by Chucksbp** [comment]
Yes you can.. you will have to change the encoder resolution from 4096 to 1024. when i had a failure with my first encoder I purchased the wrong one and got one with 300p/r set mine to 1200 resolution and it is working well. I'm not sure what might happen at when threading a small thread count at high speed? but know one would do that any way. I see no problem with the resolution. I threaded 3/4 10 with no issue and got a prefect thread.
