### ISSUE TITLE
Config Feed settings

### ISSUE THREAD

**Issue by KennethLuscombe** [clough42/electronic-leadscrew#208]
The encoder is working great. I have tested the spindel speed with a seperate tester and it matches the software settings.
However 
the gear ratio from the servo motor to the feed screw is 1 on the servo to 2 on the feed screw. My feed screw is 1.5mm
What settings do i need to change in the software to make this work out correctly.

Thanks
Ken

**Comment by Chucksbp** [comment]
you need 2 in the micro steps and i believe 150 hmm for the metric lead screw.

**Comment by KennethLuscombe** [comment]
Thank you
