### ISSUE TITLE
Not a bug... more a "can't get parts issue"

### ISSUE THREAD

**Issue by cptnmidnight** [clough42/electronic-leadscrew#218]
I have not found any other forum for this project, so I will just post here. I really want to use this system so I would like to know if anyone has a TI board they would part with. I would pay for it of course, not asking for charity I just don't have the time to reverse engineer the firmware to a teensy or one of the other fifty boards I have.

**Comment by Chucksbp** [comment]
Check with RS components, I need one they didn't show any but when i contacted them they had some in the UK they shipped DSL very fast shipping. It was a bit higher price I believe $50 US each but what can you do??? Give them a try. they have world wide offices.

**Comment by cptnmidnight** [comment]
HA! I am so fed up with this project. RS just got some in stock but they don't ship to USA. I signed up for an account and tried to check out and there is no option for shipping outside of UK

**Comment by Chucksbp** [comment]
I don't understand, RS shipped to me at the end of January, I had two boards in less than 7 days shipping with DSL. ever since i have gotten emails wanting to sell me stuff. They defiantly came from the UK!!! previously I had gotten one from TI direct through their Singapore outlet. If RS got some in Id also check some of the other sources. they may have them but haven't updated their web site. 
  The project is well worth the wait. it really works well, i have been very happy with mine. I would also recontact RS and try to get through to someone else at the facility. maybe there was a misunderstanding.

**Comment by cptnmidnight** [comment]
They state that they do on the site. The shopping cart does not have an option for shipping out of country. I did find a link on their site to the export.rsdelivers.com, but it is broken for me at the moment.
 I sent and email to them, but now they are closed for bank holiday till the 6th. Eh, what's another couple weeks, I've been delayed over a month already.

**Comment by jimhinze** [comment]
export.rsdelivers.com is up this morning and was up yesterday afternoon (I 
was able to order)

If you get that access denied error again, try a different connection.. Or 
computer

**Comment by Drulzy** [comment]
boards are allegedly in stock at ti.com. I just ordered, I had to jump through some hoops for export/import reasons but the sale has gone through. 

Last week they were not in stock, so I hope it's not an error.

**Comment by cptnmidnight** [comment]
Thanks for the update, your message got to me before my sales rep! Got the boards ordered. I already had a business account with TI so no issues ordering.

**Comment by Drulzy** [comment]
> Thanks for the update, your message got to me before my sales rep! Got the boards ordered. I already had a business account with TI so no issues ordering.

awesome. I only dropped in to see if I could let James know some how without raising an issue for no reason... @clough42

**Comment by cptnmidnight** [comment]
I have not found any other forum for this project, I think as long as we police our tickets and close them it should not be a major issue. Maybe if we open enough off topic tickets someone would be encuraged to open a proper message board. hint hint, nudge nudge
