### ISSUE TITLE
Compilation version

### ISSUE THREAD

**Issue by blackfister** [clough42/electronic-leadscrew#219]
Hi to all, I’m trying to upload code to launchpad, it states that the code was compiled with a previous version, I’m doing with latest updates as for yesterday. Anyone has came across this? Any help , greatly appreciated

**Comment by Chucksbp** [comment]
What version of code composer are you using?? From my understanding you have to use a ( version, not the 10 latest version. I had to use code composer Version 9.3 to get mine to accept the software.

**Comment by blackfister** [comment]
Update software, deleted folder, cheked connections, and I got display
![Uploading IMG_20220602_131030.jpg…]()
