### ISSUE TITLE
Can't input decimals in micro steps

### ISSUE THREAD

**Issue by dawesy72** [clough42/electronic-leadscrew#238]
By nature of how I've had to set up my gear train I've got a 12t pulley on the stepper and a 39t on the lead screw drive. This gives me a 3.25:1 ratio. When I enter 3.25 in the micro steps it causes errors when compiling. Putting 3 in works ok but obviously causes in accurate threads/feeds. Any help appreciated.

**Comment by clough42** [comment]
The steps and microsteps are multiplied together, and that's the number
that's ultimately used, so you can change both so they multiply to what you
want.  So if your steps are 200, for example, you could just set steps to
650 and micro steps to 1.  If you're also using 8:1 microstepping, you
could set steps to 650 and micro steps to 8.  Any combination that yields
whole numbers should work.

Only whole numbers are allowed.

James

**Comment by dawesy72** [comment]
Thank you James for helping me out. My steps are 1000 so I'll figure it out. 
Thanks again.

**Comment by Chucksbp** [comment]
When you figure your steps keep in mind that I believe the steps are limited to 2000. I could be wrong about that, I believe that came up in a discussion, but if you get an error you may have to divide by two micro steps to get into that sweat spot.

**Comment by dawesy72** [comment]
sorted this now thanks, yep steps limited to 2000
