### ISSUE TITLE
Resolving encoder not working with 5 volt supply

### ISSUE THREAD

**Issue by dlmock99** [clough42/electronic-leadscrew#239]
Found that my encoder would work at supply voltages higher than 5 volts but not with 5 volts.  The problem is with the internal voltage regulator in the encoder a LM78M05.  Quick fix is to remove the regulator and solder a jumper from the input and output board pads.  The fix is good only if you are using 5 volts to power the encoder.  BTW the encoder is the Omron E6B2-CWZ6C the same as James had listed.  Yes it's speced. to work at 5 to 35 volts.  Guess it depends on which company manufactures the voltage regulator.

**Comment by kwackers** [comment]
Is it a genuine Omron or a copy?
78 series regulators require the input voltage to be around 2v higher than the output to do anything so it doesn't make sense to claim a 5v supply (superficially at least).

**Comment by dlmock99** [comment]
It's the real deal.  I agree with you that the supply voltage should be higher that the regulated output.  The encoder came with the data sheet and it specs. that the supply voltage is to be 5 to 24 volt DC . Yet at 5 volts there was no output.  Removing the regulator and adding a jumper will get it working.
![IMGP0102](https://user-images.githubusercontent.com/29467210/205107153-c035cc17-d3fd-4f79-ae21-328031e32e2c.JPG)
