### ISSUE TITLE
Import tax an handling

### ISSUE THREAD

**Issue by J642** [clough42/electronic-leadscrew#24]
When ordering at Mouser.com you have to choose an address remember that at the bottom of the page under "delivery type" to choose "commercial" now you can choose DDP
Carrier Cost
DDP (Duty and customs fees paid by Mouser)
FedEx International Priority
I had to pay $ 15.57 in sales tax and $ 23.73 in customs clearance. 
Regards Jorgen Denmark

**Comment by clough42** [comment]
Good tip.  Thanks.
