### ISSUE TITLE
Mini-Lathe

### ISSUE THREAD

**Issue by fla-940** [clough42/electronic-leadscrew#25]
Has anyone converted the Harbor-Freight 7x14, SIEG style lathes and have documentation on it as to the steps you took?

**Comment by gadjet** [comment]
Would that be similar to this one?
[Warco mini hobby lathe](https://www.warco.co.uk/metal-lathes-metalworking-lathe-machine/302922-mini-hobby-lathe.html)

**Comment by TheRealGreatOldOne** [comment]
I am in the process of converting my Sieg SC4. I have all of the electronics squared away, and now need to fit the stepper, spindle encoder and drive pulleys to the lathe.

**Comment by fla-940** [comment]
> 
> 
> Would that be similar to this one?
> [Warco mini hobby lathe](https://www.warco.co.uk/metal-lathes-metalworking-lathe-machine/302922-mini-hobby-lathe.html)

Yes sir very close.....

**Comment by fla-940** [comment]
> 
> 
> I am in the process of converting my Sieg SC4. I have all of the electronics squared away, and now need to fit the stepper, spindle encoder and drive pulleys to the lathe.

Looking forward to your project out come! Keep us in the loop!

**Comment by fla-940** [comment]
> 
> 
> Would that be similar to this one?
> [Warco mini hobby lathe](https://www.warco.co.uk/metal-lathes-metalworking-lathe-machine/302922-mini-hobby-lathe.html)

Yes sir very close.....

**Comment by gadjet** [comment]
I'm going to put the ELS on my Warco mini lathe, I've already installed a stepper motor onto the lathe and control it via an Arduino but just for an auto feed, I'm currently working to add the ELS project to give it threading ability, I will put up a post on my blog when completed.
![2019-09-28 15 36 35](https://user-images.githubusercontent.com/1810366/68998621-cc1bea00-08ac-11ea-88b4-6c4f0f9de25a.jpg)
![2019-09-28 15 35 07](https://user-images.githubusercontent.com/1810366/68998624-d342f800-08ac-11ea-82d6-61c2b144494b.jpg)
![2018-11-17 16 40 21](https://user-images.githubusercontent.com/1810366/68998627-e05fe700-08ac-11ea-8f2a-84b84107daf4.jpg)

**Comment by TheRealGreatOldOne** [comment]
Here’s my work so far:
![90519B44-3201-4AB1-A17C-0671778B06E3](https://user-images.githubusercontent.com/43447047/68999898-42294c80-08bf-11ea-86ed-8377ab17afc7.jpeg)
![8F481F13-2F2A-459C-BB6A-36E831D296A2](https://user-images.githubusercontent.com/43447047/68999899-42294c80-08bf-11ea-8366-fc3e22b8859f.jpeg)
![3C6C3B23-D151-41A8-81DC-C903B8B2F8C1](https://user-images.githubusercontent.com/43447047/68999900-42294c80-08bf-11ea-94b0-339e2590dbb7.jpeg)
![B7C8B3F1-561F-47E1-BCCA-93983CE15168](https://user-images.githubusercontent.com/43447047/68999901-42294c80-08bf-11ea-8039-51e4ee90edf1.jpeg)
![DE65CDD9-4A2D-4410-81A2-358DDFB67A61](https://user-images.githubusercontent.com/43447047/68999902-42c1e300-08bf-11ea-94b8-fadeb1b1102c.jpeg)
![518DF57F-B5D4-4B7D-AFF3-5BFD3EC4CAD5](https://user-images.githubusercontent.com/43447047/68999903-42c1e300-08bf-11ea-92a1-fc5d61d28a34.jpeg)
![FBA7D817-CAA7-4423-8A49-D99794704B36](https://user-images.githubusercontent.com/43447047/68999904-42c1e300-08bf-11ea-8e43-e4626b48ce3f.jpeg)
![F99AD95F-6863-4DF2-A554-6A51EAB64950](https://user-images.githubusercontent.com/43447047/68999905-42c1e300-08bf-11ea-9af3-46915e1e2104.jpeg)
![8B7A3BC2-B8A9-49E5-9B5E-10E5D5808C01](https://user-images.githubusercontent.com/43447047/68999906-42c1e300-08bf-11ea-9586-fee2378063c9.jpeg)

**Comment by gadjet** [comment]
Looks good, where did you get your large enclosure from?

**Comment by TheRealGreatOldOne** [comment]
Amazon:
[https://www.amazon.co.uk/380mm-Junction-Weatherproof-Waterproof-Enclosure/dp/B07B66ZH1G/ref=pd_nav_hcs_rp_2/260-5082970-1356367?_encoding=UTF8&pd_rd_i=B07B66ZH1G&pd_rd_r=3a7b5a9d-d51d-4815-a229-3c198e51c3a8&pd_rd_w=qLMlq&pd_rd_wg=qYRmx&pf_rd_p=f6051d3e-949c-405f-913b-20ea296ef01b&pf_rd_r=VT6EJ383BKPH1Z4R72CM&psc=1&refRID=VT6EJ383BKPH1Z4R72CM](url)

**Comment by clough42** [comment]
That looks really nice.

It looks like you have a common ground between the motor power supply and
the logic 5V supply.  Some people have had trouble caused by motor noise
interfering with the logic.

James

**Comment by TheRealGreatOldOne** [comment]
> That looks really nice. It looks like you have a common ground between the motor power supply and the logic 5V supply. Some people have had trouble caused by motor noise interfering with the logic. James
> […](#)

Thanks James. I’ll see how I get on once I have the motor and encoder mounted on the lathe, and re route if I get into issues.

**Comment by TheRealGreatOldOne** [comment]
![IMG_0475](https://user-images.githubusercontent.com/43447047/69253703-f3283380-0bac-11ea-93e9-4c791b2b28d5.jpeg)
![IMG_0476](https://user-images.githubusercontent.com/43447047/69253704-f3283380-0bac-11ea-97d9-17ec6cff17f3.jpeg)
[https://www.thingiverse.com/thing:3989108](url)
[https://www.youtube.com/watch?v=lNFqjpXHLy4](url)

The RPM agrees with the lathe... Ish. It jumps around a bit, but not a lot. Has anyone else encountered this?

**Comment by clough42** [comment]
It's updating 10 times per second by default.  You can slow it down by
modifying  RPM_CALC_RATE_HZ in Configuration.h.  Setting it to 2 would
update twice per second, for example.

Slowing it down will make it less responsive, but also clean up some of the
jitter.

James

**Comment by TheRealGreatOldOne** [comment]
USB socket added to the control box for easy firmware upgrades. Servo / Hybrid stepper mounted, Control box hung on the back of the lathe, change gear cover modified to fit over the encoder and servo. Oh, and wired in so it all turns on when the lathe is switched on. :)

![IMG_0491](https://user-images.githubusercontent.com/43447047/69503223-76c88400-0f0f-11ea-84f5-22cd8d3842f6.jpg)
![IMG_0482](https://user-images.githubusercontent.com/43447047/69503224-76c88400-0f0f-11ea-97a9-7d2f186e8398.jpeg)
![IMG_0483](https://user-images.githubusercontent.com/43447047/69503225-76c88400-0f0f-11ea-8c1e-25cfed6fc9b4.jpeg)
![IMG_0484](https://user-images.githubusercontent.com/43447047/69503226-76c88400-0f0f-11ea-8411-11bd456a9bda.jpeg)
![IMG_0485](https://user-images.githubusercontent.com/43447047/69503227-76c88400-0f0f-11ea-90fa-f65fef5ad44a.jpeg)
![IMG_0486](https://user-images.githubusercontent.com/43447047/69503228-77611a80-0f0f-11ea-8a5b-0df9ba86377c.jpeg)
![IMG_0490](https://user-images.githubusercontent.com/43447047/69503229-77611a80-0f0f-11ea-8814-c1e1fa779dc2.jpeg)
![IMG_0492](https://user-images.githubusercontent.com/43447047/69503230-77611a80-0f0f-11ea-804f-3a70a9dbd93c.jpeg)
![IMG_0474](https://user-images.githubusercontent.com/43447047/69503231-77611a80-0f0f-11ea-9061-ecd1ce38dbef.jpeg)
![IMG_0475](https://user-images.githubusercontent.com/43447047/69503232-77611a80-0f0f-11ea-8047-64e540ea9003.jpeg)
![IMG_0476](https://user-images.githubusercontent.com/43447047/69503233-77611a80-0f0f-11ea-90bc-9e8d03ab9540.jpeg)

https://youtu.be/Yq_rMzeSS1s

What I have encountered whilst testing is I can quite easily get the driver alarm to trigger... depending on spindle speed and thread pitch / feed selected. My lathe has a top speed of 2000rpm, and with the pulley ratio of 3:1 and then whatever the multiplier is for feed - you can quite easily top out the max RPM of the servo. 

I've just made a chart of max possible spindle speed for a given feed. For the most part, the feeds are fine. it's the thread pitches that can make it go down... but I very much doubt I'd ever need to do any single point threading above a couple of hundred RPM anyway. And the convenience of not having to bugger about with change gears far outweighs the possible need to do a 5 TPI thread at over 1000RPM

**Comment by TheRealGreatOldOne** [comment]
Final piece of the puzzle - mounted the display.

![DE5D9C2B-6945-48BB-BD49-9DA914A0D000](https://user-images.githubusercontent.com/43447047/69664495-671c7d00-1080-11ea-9cbb-b4e9fd1dc649.jpeg)
![52930DED-3EB0-46F6-AF64-68A526303EB9](https://user-images.githubusercontent.com/43447047/69664496-671c7d00-1080-11ea-9e19-1c26f37de722.jpeg)

**Comment by clough42** [comment]
Thanks for sharing your build.  This is awesome!

James

**Comment by buzzkc** [comment]
> I'm going to put the ELS on my Warco mini lathe, I've already installed a stepper motor onto the lathe and control it via an Arduino but just for an auto feed, I'm currently working to add the ELS project to give it threading ability, I will put up a post on my blog when completed.
> ![2019-09-28 15 36 35](https://user-images.githubusercontent.com/1810366/68998621-cc1bea00-08ac-11ea-88b4-6c4f0f9de25a.jpg)
> ![2019-09-28 15 35 07](https://user-images.githubusercontent.com/1810366/68998624-d342f800-08ac-11ea-82d6-61c2b144494b.jpg)
> ![2018-11-17 16 40 21](https://user-images.githubusercontent.com/1810366/68998627-e05fe700-08ac-11ea-8f2a-84b84107daf4.jpg)

Would you be willing to share your bracket design? I've got a 7x14 I'd like to adapt this to.

**Comment by gadjet** [comment]
No problem, I'll put it on thingiverse and post the link here.

**Comment by buzzkc** [comment]
> No problem, I'll put it on thingiverse and post the link here.

No rush on this, I realize with all that's going on with the world that this isn't a priority. I was wondering what gear tooth count you're using on the encoder. It looks like my encoder and display should come by this weekend, so may mess around with programming the launchpad...Thanks!

**Comment by gadjet** [comment]
Hi,
I've added the files to Thingiverse.
[https://www.thingiverse.com/thing:4232927](url)

**Comment by buzzkc** [comment]
Thank you!

**Comment by pikolo335** [comment]
Hi !what king of hybrid motor controller is this that you have? Can i have the wiring please?

**Comment by Vrossi050** [comment]
Same as what James recommended from Automation Technologies.


https://www.automationtechnologiesinc.com/products-page/hybrid-servo-system/hybrid-servo-drive-kl-5080h/


--- Original message ---

**Comment by davidgleach** [comment]
For what its worth, here is my conversion on my Seig mini lathe.  It works very well. 
I 3D printed the belts, pulleys, several of the mountings, control panel and the extension to the end cover.
I have removed the cross slide to allow the provision of a very stiff tool post.  The  feed screw can be rotated manually.  consequently, I have included a switch to isolate the stepper motor for manual feeding.
![P9210135](https://user-images.githubusercontent.com/66470797/93955901-2a024380-fd94-11ea-80b4-8e84ace86952.JPG)
![P8290129](https://user-images.githubusercontent.com/66470797/93956001-764d8380-fd94-11ea-8b09-07aa893f4ae1.JPG)

**Comment by JonWoellhaf** [comment]
Very nice, David!

**Comment by clough42** [comment]
Wow.  That looks really nice!

**Comment by davidgleach** [comment]
Thanks James.  In order to improve stiffness of the little Seig lathe, I 
have removed the top slide and use the lead screw in manual mode (A 
simple DRO ensures accuracy).  Hence I hard wired a switch into the 
motor circuit so that I could disable it's supply power.  This works 
pretty well for me as I only thread occasionally.
Very grateful for your design and videos - they have taught me a lot.

Cheers
David
David Leach



Home: 03 5310 6313

Mob:    0416 119 381




------ Original Message ------

**Comment by clough42** [comment]
I just released version 1.3.01 so you can now use the power switch to turn off the motor and still retain the RPM readout.
