### ISSUE TITLE
Control panel box/enclosure

### ISSUE THREAD

**Issue by pbrubaker** [clough42/electronic-leadscrew#276]
Hey all, it's not mentioned in the docs or on the wiki, and I couldn't find a previous issue asking.  What is the mfr/part# of the enclosure/box for the control panel kit?

**Comment by sonex128** [comment]
BUD Industries CU-124 Aluminum Econobox 4.38" L x 2.38" W x 1.21" H,
Natural
https://a.co/d/gY3YYci

**Comment by pbrubaker** [comment]
Thank you!
