### ISSUE TITLE
Key&LED only works with USB power to launchpad

### ISSUE THREAD

**Issue by Bahr01** [clough42/electronic-leadscrew#280]
EDIT: two problems; first, led&keys NFG; 2nd problem, Clough42 interface board was not supplying 3v to LED&Key, I just connected the jumpers back on the Launchpad and it all works fine, even supplying external 5v to interface board.

I'm having an issue which has continued over 2 launchpads and 2 ELS boards from Clough42:

After flashing board, ELS will function perfectly when powered through USB on Launchpad with jumpers installed.
When using 5v power supply (jumpers removed), it just has a single red light on the board and nothing on the LCD.
I've verified 5v at the +5V pin and +3V at the correct pin.

This has me a bit stumped. I'd assumed it was a faulty board, but after replacing both, it's the same.
![PXL_20240111_030137303 MP](https://github.com/clough42/electronic-leadscrew/assets/156276979/cd78266b-b225-4050-9e46-675e68c910b0)

**Comment by Chucksbp** [comment]
I would try a differant power supply and also double check the switch positions. some times you have to flip those back and fort a few times to eliminate the goo from the adhiseve cover. lastly check your continuity tp the board for the power  pins.

**Comment by Bahr01** [comment]
Turns out to be dud LED&Keys, I just had 3 of them and I think what's happening is it works on my desk when I flash the board and test it, then my Meanwell 5v DIN psu I'm using to power the ELS board somehow fries the LED&Key, then I think it only works with USB.

I tested these back at my desk and they don't work at all, then found an LED&KEY I hadn't put in service and it works fine. I just need to find out why my meanwell psu is killing these boards, it's 5.0v on the money output, I'll have to put a scope on and check ripple.

**Comment by Chucksbp** [comment]
This is the pow supply I have used on several electronic power supplies and it has worked well on all including the ELS.    https://www.amazon.com/gp/product/B01ALGGK2O/ref=ppx_yo_dt_b_asin_title_o05_s00?ie=UTF8&psc=1

**Comment by Bahr01** [comment]
So I have a final resolution; two things were wrong; I had a bad led&key (qc is shite on those). 2nd problem, my clough42 interface board was bad and not powering the launchpad properly. My workaround was to actually leave the jumpers connected on the launchpad and now it works perfectly. Still some flicker which I'm chasing down, but still usable.
The interface boards seem rather delicate, I have another in case it all goes south.
