### ISSUE TITLE
CL57T Controller not running motor from ELS control

### ISSUE THREAD

**Issue by MZamalis** [clough42/electronic-leadscrew#294]
Hello Everyone.  I'm working on my first build and using Clough42 kit with version 1.4.0.  I have no issues on the RPM detection side nor ton the user interface.

For motor I chose a NEMA23 closed loop stepper with a CL57T v4 controller.  I have the controller fed by a 24v power supply and the controller has a switch that can be set to 24v signal level or 5v; I'm set to 5v.

I have no movement of my stepper from the ELS.  To verify I used a 5V jumper on the controller PUL+/PUL- and the motor turns just fine.  When the power supply is unplugged I can turn the motor shaft by hand but with power supply active is it tight.

Wiring for Pulse, Enable, Direction is as per James' diagram; very straightforward.  One difference from James' wiring is that this controller has pins ALM, BRK, and COM-.   I connected Clough42 FLT+ to ALM and FLT- to COM-.  I have also tested this with those lined disconnected as well as jumpered.  I also tested with "#define USE_ALARM_PIN" commented out.  No success

I have tried this with the enable pin inversion active in code and commented out.  No success.

I started with the TI board ungrounded, but also tested with a GND pin from the TI board pulled back to V- on my power supply.  No success.

I have verified continuity from screw to screw on both ends of the terminal connectors. 

Some pics of my bench setup are [HERE](https://photos.app.goo.gl/nZuZtmV9Vi8HL9kT7).

If anyone with experience with this controller can chime in that would be great; or any other troubleshooting guidance for that matter.

Thanks in advance,
Mike

**Comment by Turner75** [comment]
Hi
Don't know if you have used stepper motors before. First principals. They
only move when the four motor inputs are sequenced in the right order. No
power on any line, motor can be turned by hand easily. Any power flowing
into a coil pair will make motor hard to turn, condition locked.  Connected
up to the controller with enable/ direction lines connected but not clock
pulse input. Manually pull that line down intermittently, just tap down to
0volt. Motor should take jerky steps. That will establish that the step
signals are activating motor. Connect back up the clock signal line and try
the same test with the clock line disconnected where it comes out of the
DSP board. If the motor moves, then the DSP is not generating the clock
signals in response to the encoder movement.

These are very rudimentary tests without the use of test instruments. The
very simplest test equipment that you can use is a lamp connected to two
leads. Could be an led with a series resistor. Say 470 ohms. It will give
indications of the state of the signal lines, 5volt or 24volt, plus the
signal polarity, the led is a diode, conducts. Lights only in one
direction. Hope this helps a little, baby steps.

**Comment by MZamalis** [comment]
We should close this topic out.  Turns out my error was inconsistent wiring.  I had intermittent connection on the lines from boost board to controller.  I had it in my head that they were all good; checked them and got continuity; but I now know that was only when pressing down on them.  2 wires were the issue.

Turner75, thanks for hopping in with some guidance.

Thank you all
