### ISSUE TITLE
Launch Pad j12 connection

### ISSUE THREAD

**Issue by Vrossi050** [clough42/electronic-leadscrew#36]
I broken two traces on the Launch Pad at J12. I can't find documentation or schematic from TI web site on specific traces. What would it take to move to J13 if possible? Or can you tell me where J12 1A 1B and 1I trace too? Any help would be appreciated

**Comment by clough42** [comment]
The TI documentation is here:

http://www.ti.com/tool/LAUNCHXL-F280049C

The PDF includes full schematics

James

**Comment by Vrossi050** [comment]
Thank you James!
