### ISSUE TITLE
Hybrid Stepper not moving properly - SOLUTION

### ISSUE THREAD

**Issue by t3kboi** [clough42/electronic-leadscrew#41]
OK, 

I spent way too much time down electrical rabbit holes on this one....

KL-5080H Hybrid Servo Drive / KL23-2N-1000 Nema 23 hybrid stepper

Problem: everything works, but the hybrid stepper only moves a few steps in either direction at very slow speed, and then stops moving.  Holding the stepper frame, you can feel the step pulses continuing, but no more rotation, until re-powering the driver.

Solution: Unplug the stepper encoder from the driver, and plug it into the 6' cable that came with it.  Apparently the pinout from one end of the cable to the other is not straight-through.  Plugging the motor directly into the drive causes the problem.

**Comment by clough42** [comment]
Yeah... This catches a lot of people.  I need to put it in a
troubleshooting page

James

**Comment by t3kboi** [comment]
Not really a problem with your ELS project - but definitely something that should be included in the text/documentation at Automation Technology....

:-)

**Comment by pauly7300** [comment]
I experienced the same prob and wrote them a "passionate" email asking them to mention that the extra cable was NOT an extension cable and was required in order to use.  They have since put up another diagram on the listing but it doesn't directly mention the cable.

**Comment by themadreefer** [comment]
> OK,
> 
> I spent way too much time down electrical rabbit holes on this one....
> 
> KL-5080H Hybrid Servo Drive / KL23-2N-1000 Nema 23 hybrid stepper
> 
> Problem: everything works, but the hybrid stepper only moves a few steps in either direction at very slow speed, and then stops moving. Holding the stepper frame, you can feel the step pulses continuing, but no more rotation, until re-powering the driver.
> 
> Solution: Unplug the stepper encoder from the driver, and plug it into the 6' cable that came with it. Apparently the pinout from one end of the cable to the other is not straight-through. Plugging the motor directly into the drive causes the problem.

i had the exact same issue with mine...

**Comment by clough42** [comment]
I added this to the troubleshooting documentation.  Closing the issue.
