### ISSUE TITLE
Software installed and working 👍

### ISSUE THREAD

**Issue by Johnboy251** [clough42/electronic-leadscrew#52]
James 
Software installed and encoder & hybrid stepper working ok. The next phase is to get the hardware mounted on the lathe using suitably designed brackets/mountings. I will be using this on a metric lead screw with a 3mm pitch.

I’ve incorporated the Jon Woellhaf fast scroll/ auto increments mods (#48) to the code which works well. 

Great project...

Best regards 
John 🇬🇧

**Comment by JonWoellhaf** [comment]
John,

I'm delighted you had the courage to try my button hack. :) Glad it's working for you!

Jan (Yan)

**Comment by Johnboy251** [comment]
Jan & James...

Yes you fast scroll is a really useful addition 👍
I’m looking at putting the setup that has been selected into a non volatile (flash?) memory location so when power is turned off the configuration is not lost. This would be helpful if Power was lost through a ‘brown out’ or power cut.
My coding skills are a bit to be desired to say the least but I added extra trailing zeros in the tables and got them to work ok.

Thanks for the email.

Regards
John
