### ISSUE TITLE
Gear Ratio

### ISSUE THREAD

**Issue by Vrossi050** [clough42/electronic-leadscrew#58]
Mr Clough,
I have Grizzly G9972 lathe. I have been trying to get the ratio for threading right. So far no luck.The Configiration.h file reads:
Encoder uses 1:1 ratio from the spindle(45T to Idler 45T) to 60T stacked on the idler and 60T on the encoder. Resolution set to 4096
Servo motor same as yours 1000 P/R  
Servo motor 24T to 72T L/S 3:1 ratio
Stepper Resolution 1000
Microsteps 3
Lead screw TPI set to 8
What am I missing? Any help would be greatly appreciated.

Thank you,
Vrossi8050

**Comment by JonWoellhaf** [comment]
When you lhread 8 TPI, what TPI do you get?

**Comment by Vrossi050** [comment]
I was trying 11 TPI. The leadscrew is 8 TPI. What the result is looks 32 TPI or smaller

**Comment by JonWoellhaf** [comment]
Please try 8 TPI, because that should be 1:1 spindle to leadscrew, since you have an 8 TPI leadscrew. See if you get 24 TPI on the work.

**Comment by Vrossi050** [comment]
I will give it a try over the weekend. Thank you

**Comment by Johnboy251** [comment]
Hi Vrossi8050

Are you using a hybrid stepper or servo,to drive lead screw?
Regards 
John

**Comment by Johnboy251** [comment]
I’ve read you initial message - you mention the you have the same motor as James. James is using a hybrid servo not a stepper.

You need to set the Mictosteps for that motor to 1 

Take a look at James’s YouTube video ELS part 10 about 19 minutes in. James explain things there.

John

**Comment by Johnboy251** [comment]
Hi again...

If your try for 11 TPI with your configuration/setup you would get 33 TPI with your lead screw. ✔️

**Comment by JonWoellhaf** [comment]
Hi, Johnboy.

I agree the microsteps need to be set to 1, but only if the hybrid servo is 
driving the leadscrew directly.

In his configuration.h comments, James writes, “NOTE: If you are using a 
servo drive with something other than a 1:1 drive ratio, you can use the 
STEPPER_MICROSTEPS to compensate. For example, if you have a servo 
configured for 1000 steps/revolution and it drives the leadscrew through a 
3:1 reduction, you can set STEPPER_RESOLUTION to 1000 and STEPPER_MICROSTEPS 
to 3."

In his Part 5 video starting at 28:52, James mounts a 24 tooth pulley on the 
hybrid servo and a 72 tooth pulley on the gearbox input shaft. I think I 
remember him saying he set the gearbox to 1:1. So he's using the 3:1 
reduction mentioned above, and I assume has set his microsteps to 3, even 
though in his Part 10 video, which you referenced, James sets it to 1.

I'm confused. What do you think?

It seems to me Vrossi050 is driving his leadscrew directly, but has his 
microsteps set to 3.

**Comment by Vrossi050** [comment]
Hi all,
Thank you for your help on this.
I have configuartion.h file set to :
3 microsteps
1000 P/R.
The as mentioned above yes I have a 3:1 ratio as James shows 24T on Hybrid servo motor and the lead screw input is 72T . I wonder if the hardware version matters or?

**Comment by JonWoellhaf** [comment]
You have the gearbox set to 1:1 input shaft to leadscrew, right?

**Comment by Vrossi050** [comment]
Yes the gearbox is set 1:1.

**Comment by JonWoellhaf** [comment]
I have another thought.

When you changed the values in configuration.h, and downloaded the program to the LAUNCHXL board, are you sure you were in Release mode?

**Comment by Johnboy251** [comment]
Hi Jan & Vrossio50

I thought I had it - I’m not sure now.😳 I hope James can through some light on what’s happening.

Hope you’re all keeping well.
John

**Comment by Johnboy251** [comment]
Jan & Vrossio50

Just looked at James YouTube video ELS Part 11  about 15 minutes in...
I’m not sure if that helps.

**Comment by JonWoellhaf** [comment]
Did you see my question about building in Release mode?

**Comment by Vrossi050** [comment]
Yes I flashed the Release to the board.

**Comment by Vrossi050** [comment]
I reflashed the board and no changes in thread until I change the gearbox dials A=1 and B selected. 
![20200321_130528](https://user-images.githubusercontent.com/53663633/77235679-356e7b00-6b75-11ea-844a-2e8f0fcf9bc6.jpg)

**Comment by Johnboy251** [comment]
![7A6DD2DD-B620-493A-A6FE-49B79772FE9D](https://user-images.githubusercontent.com/51803701/77235794-c151c880-6bb0-11ea-82cc-2f5694e1b032.jpeg)

You encoder gear train looks like this?
John

**Comment by Vrossi050** [comment]
No just 60 to 60T. The 45 sits behind the 60
![15848222126164337592222346715114](https://user-images.githubusercontent.com/53663633/77235929-34d6e400-6b77-11ea-9d31-7f82bdcf9b7c.jpg)

**Comment by Johnboy251** [comment]
I see the pcd of the gears is different but I can’t see how it’s driven. 😳

**Comment by Vrossi050** [comment]
Next to the black 45t is the spindle gear also 45t but larger in diameter.

**Comment by Vrossi050** [comment]
![Screenshot_20200321-150827_Camera](https://user-images.githubusercontent.com/53663633/77237493-de24d680-6b85-11ea-8e3f-5397b4954a69.jpg)

**Comment by Johnboy251** [comment]
Forgive me if I’m wrong -

I have configuartion.h file set to :
3 microsteps
1000 P/R.
The as mentioned above yes I have a 3:1 ratio as James shows 24T on Hybrid servo motor and the lead screw input is 72T

I still think microsteps should be set to 1 not 3
Could you try it for me?

**Comment by Johnboy251** [comment]
Gears on encoder - that’s the same effectively as my diagram giving you as you say 1:1 ✔️👍

**Comment by Johnboy251** [comment]
I’m turning in now for the night... let us know how you get on with this. 🤔👍

**Comment by Vrossi050** [comment]
Sure.

**Comment by Vrossi050** [comment]
I tried 1 microsteps and puts me back to where I started. Maybe cut resolution in half on the encoder or increase steps to 4. We shall see tomorrow. Any thoughts on this?

**Comment by Johnboy251** [comment]
Hi Vrossi050
I’ll read though the messages again and some of James’s video again when I get a chance. Let’s see what we can achieve. 👍
Regards, ConfusedJohn.😳

**Comment by JonWoellhaf** [comment]
Vrossi050, I have a new thought.

Can you verify the RPM display is accurate?

**Comment by Vrossi050** [comment]
Hi Johnboy251,
I just tested the RPM with a tachometer on the chuck. The ELS display and tachometer match. I marked all the gears and pulleys and they are also 1:1 except for the 24t to 72T servo to Leadscrew which is 3:1. Any thoughts?

**Comment by JonWoellhaf** [comment]
Have you tried cutting 8 TPI?

**Comment by Vrossi050** [comment]
Yes see above photo. Set on 8 TPI but it looks like 16 TPI.

**Comment by JonWoellhaf** [comment]
Thanks, I missed that photo.
So to summarize,
    11 TPI looks like 32 or 33
    8 TPI looks like 16
    tach readout is correct.
Without changing anything in the code, please try cutting 8 TPI (again), 11 TPI (again), 24 TPI, and 32 TPI.
This is a very interesting problem, but I imagine it's quite frustrating for you. Sorry. :)

**Comment by Vrossi050** [comment]
It is quite the challenge. Thanks for your help.

**Comment by Vrossi050** [comment]
with the gear box set at 1 to 1?

**Comment by JonWoellhaf** [comment]
Yes! Always.

**Comment by Vrossi050** [comment]
8 TPI 
![15850994668683850703449803369934](https://user-images.githubusercontent.com/53663633/77492047-b9866400-6dfc-11ea-90fd-de4cfcfc55e1.jpg)
![15850994875707252841678065621363](https://user-images.githubusercontent.com/53663633/77492062-c86d1680-6dfc-11ea-83cf-4ddfedffd798.jpg)

**Comment by Vrossi050** [comment]
![15850995230848765459985594691090](https://user-images.githubusercontent.com/53663633/77492086-dae75000-6dfc-11ea-94c5-835960cd1d2a.jpg)

**Comment by JonWoellhaf** [comment]
How many teeth on gear a and gear b?

**Comment by JonWoellhaf** [comment]
Please mark a reference on the spindle and leadscrew, then rotate the spindle one turn. Does the leadscrew rotate one turn?

**Comment by Vrossi050** [comment]
In the gearbox? I don't know. I haven't had it open. 11tpi looks the same as 8tpi
![15851001796212138849660884194934](https://user-images.githubusercontent.com/53663633/77492672-61506180-6dfe-11ea-9284-17abfb34ba24.jpg)

**Comment by JonWoellhaf** [comment]
No, the end gears on the left.

**Comment by Zymurgy42** [comment]
Initially I had similar issues, caused by trusting the specs in my manual for Leadscrew pitch. I physically measured (manual was wrong) input correct details;

#define LEADSCREW_HMM 250

And issue gone. A quick scan of this message doesn't show 'PITCH'.

**Comment by Vrossi050** [comment]
I measured with caliper last week. Came up with 8tpi. I defined that in configuration.h file. Tomorrow reflashed board to reflect 3 microsteps and 1000 p/m for servo settings.

**Comment by Vrossi050** [comment]
45t idler to 45tspindle 60t idler to 60t encoder. See photos above.

**Comment by JonWoellhaf** [comment]
OK. Another new thought:

With the leadscrew marked, and the pulley attached directly to the gearbox marked, turn the pulley one rotation and confirm the leadscrew turns one rotation.

**Comment by Johnboy251** [comment]
I agree with Jan - can you find out what gear setting you need to be to get 1:1 though the gearbox?

The other thing - could you confirm the pitch or TPI of the lead screw?

I’ve been working out various gear settings to try to understand where the error is hiding. In the gear box setting of ‘1 A’ there is a compound gear (120/127) that in the gear train which under mechanical configuration will give you either metric pitch or TPI with the reverent change gears.
John
P.S. stay well & away from this virus.🤞

**Comment by Vrossi050** [comment]
I just marked the lead screw and pulley. It is set one to one with each other.One revolution and all the hash marks line up. Both gear box knobs are set all the way to the left. Just as James shows in his video. He says his is 12 TPI.  Maybe I should adjust encoder resolution and or Micro steps in Configuration .h file?.

Stay safe as well !!

**Comment by JonWoellhaf** [comment]
I've been looking at the Grizzly G9972z manual.

It looks to me that change gear 'a' rotates at spindle speed and drives change gear 'b' through a 127 tooth idler. Thus, the gearbox input shaft, to which 'b' is attached, rotates at fraction a/b of spindle speed. The number of teeth on the idler is immaterial. But note the change gear configuration is different for cutting metric threads.

To cut 8 TPI, the lever configuration is IB, and the change gears are 'a' = 35 and 'b' = 70. Thus, the gearbox input rotates at half spindle speed, and the gearbox multiplies its input by 2, which turns the leadscrew at spindle speed, as required for an 8 TPI leadscrew to cut an 8 TPI thread. So in setting IB, the gearbox turns the leadscrew by one half its input shaft speed.

To cut a 16 TPI thread, the same change gears are used, but the levers are shifted to IA. To cut a 16 TPI thread with an 8 TPI leadscrew, the leadscrew must turn at half spindle speed. So in setting IA, the gearbox turns the leadscrew the same speed as its input shaft speed.

So I agree lever setting IA is 1 to 1 gearbox input shaft speed to leadscrew speed.

**Comment by Vrossi050** [comment]
So where do I go from here?

**Comment by Vrossi050** [comment]
![image](https://user-images.githubusercontent.com/53663633/77593366-530f4d80-6eb1-11ea-89f2-362f0111a1f8.png)
The parts manual shows inch lead screw

**Comment by JonWoellhaf** [comment]
Indeed! That is the question. We seem to have eliminated everything. This just gets interestinger and interestinger!

OK. How about this:

Set the ELS to inch and 8 TPI, then rotate the spindle by hand and watch the leadscrew. Does the leadscrew turn one turn for each turn of the spindle?

**Comment by Johnboy251** [comment]
Well I spent most of the morning checking gear ratio's to try to determine the settings on the gear box selector.
I haven't come up with anny conculsions yet... :-(

**Comment by Vrossi050** [comment]
Can't turn by hand. Servo motor engaged

**Comment by JonWoellhaf** [comment]
Turn the spindle, not the gearbox pulley.

**Comment by JonWoellhaf** [comment]
James Clough, are you watching this conversation and laughing?

**Comment by Vrossi050** [comment]
I got it. One revolution of the chuck by hand and the lead screw rotates about a quarter. It takes 12 revolutions by hand of the chuck to equal 1 revolution of the lead screw

**Comment by JonWoellhaf** [comment]
OK. Now we’re on to something!

This is with the gearbox levers set to I A, correct?

This is why your threads are way too fine.

**Comment by Johnboy251** [comment]
I'm in the UK - so it past my bedtime! perhaps I'll dream about this tonight (or it will keep me awake!) and I might wake up with the answer!! 
Good Night all....

**Comment by Vrossi050** [comment]
Yes just as the picture shows.
Ok good night stay safe!!!

**Comment by Johnboy251** [comment]
Thanks... John

**Comment by JonWoellhaf** [comment]
Be sure and let us know if you wake up with the answer!

**Comment by Johnboy251** [comment]
At the moment - It's good to wake up in the morning and not feel wood either side of you... :-0

**Comment by JonWoellhaf** [comment]
Please review the settings in configuration.h.

Something has changed, because a while back you got 16 TPI when set to 8.

At 12:1 spindle to leadscrew, you would get 96 TPI.

**Comment by Vrossi050** [comment]
I got the 16 by  I and B. That;s funny right there!! I don't disagree with that. I set it back to Microstep 1
1000 P/R

**Comment by JonWoellhaf** [comment]
Please change to microsteps 3 and perform the test again. I am certain microsteps = 3 is correct for your configuration.

**Comment by Vrossi050** [comment]
Sorry I had it set to Microsteps 3 1000 P/R when I cut the 8TPI and came up with the 16TPI with the knobs set to l and B

**Comment by Vrossi050** [comment]
In the configuration.h file the lead screw entry should it be 08 or single digit 8?

**Comment by Vrossi050** [comment]
Part 4 @ (16:50) of build shows stepper driver programming. I will check those settings as well including Resolution of encoder mounted on the back of the hybrid servo. Which I had changed early on.

**Comment by JonWoellhaf** [comment]
Yes! That is where I was going to go next, too.

With the change of microsteps back to 3, did you repeat the experiment of turning the chuck by hand?

**Comment by Vrossi050** [comment]
After my day job today or tomorrow.

**Comment by Vrossi050** [comment]
Ok so I tried to reprogram the Servo driver and now it locks up. So I will reset if I can and try again. This is frustrating.

**Comment by Vrossi050** [comment]
OK reset ELS  to 3 Micro steps and 1000p/r. The driver for the Servo is also rest. Same result. Even after trying IA, IB and several other combinations. How should the file read for the Servo driver?

**Comment by JonWoellhaf** [comment]
With the gearbox set to IA, how many turns of the spindle to get one full turn of the leadscrew?

**Comment by Vrossi050** [comment]
12

**Comment by JonWoellhaf** [comment]
Just to be certain I understand:

With microsteps = 1, it took 12 rotations of the spindle to rotate the leadscrew one turn.

With microsteps = 3, it took 12 rotations of the spindle to rotate the leadscrew one turn.

Is that correct?

**Comment by Vrossi050** [comment]
Had it on wrong setting. Sorry. Retrying test

**Comment by Vrossi050** [comment]
4 Chuck revolutions = 1 rotation on the lead screw
Microsteps=3
P/R = 1000

**Comment by Vrossi050** [comment]
![image](https://user-images.githubusercontent.com/53663633/77798836-defbb380-7030-11ea-9406-8d628e9aeb00.png)

**Comment by JonWoellhaf** [comment]
OK, good! That is exactly what I expected to see.

**Comment by JonWoellhaf** [comment]
I believe we have found the problem.

Please set Pulses/Revolution to 1000 and Encoder Resolution to 1000 and retest.

**Comment by Vrossi050** [comment]
on the els or servo driver?

**Comment by JonWoellhaf** [comment]
On the servo driver.

**Comment by Vrossi050** [comment]
![image](https://user-images.githubusercontent.com/53663633/77799749-aeb51480-7032-11ea-8e9f-efe7e263215d.png)

**Comment by Vrossi050** [comment]
changed. Does it look correct now?

**Comment by JonWoellhaf** [comment]
Correct.

**Comment by JonWoellhaf** [comment]
Yes. Be sure to save the new settings.

**Comment by Vrossi050** [comment]
Retest shows 4 revolutions = 1 lead screw rotation
Gear box set one to one

**Comment by JonWoellhaf** [comment]
Please import the servo controller settings again and confirm that both Pulses/Revolution and Encoder Resolution are set to 1000.

**Comment by Vrossi050** [comment]
It immediately goes into alarm.

**Comment by JonWoellhaf** [comment]
How many times did the alarm led flash?

**Comment by Vrossi050** [comment]
I didn't count.

**Comment by JonWoellhaf** [comment]
Have you looked at the servo controller programming video at <https://www.youtube.com/watch?v=iEMt9jad3E8>?

The all too brief controller manual says the alarm led will flash 1, 2, or 7 times per cycle. I’m guessing it flashed seven times.

Just a guess, but please try changing Encoder Resolution back to 4000, while leaving Pulses/Revolution at 1000.

**Comment by Vrossi050** [comment]
This is the ELS setting
![image](https://user-images.githubusercontent.com/53663633/77801909-048bbb80-7037-11ea-89c9-c4d232b8aa12.png)

**Comment by JonWoellhaf** [comment]
That is correct.

**Comment by Vrossi050** [comment]
test shows 1 revolution of chuck = 1 revolution of lead screw

**Comment by JonWoellhaf** [comment]
I just checked the KL23-2N-1000 hybrid servo motor datasheet and it says the encoder is 1000 lines.

It that the motor you have?

**Comment by Vrossi050** [comment]
yes

**Comment by JonWoellhaf** [comment]
Yea! It’s finally working correctly!

Just for confirmation, your settings are:

ELS:
    LEADSCREW_TPI 8
    STEPPER_MICROSTEPS 3
    STEPPER_RESOLUTION 1000

KL-5080H Hybrid Servo Drive:
    Pulses/Revolution = 1000
    Encoder Resolution =  1000

Correct?

**Comment by Vrossi050** [comment]
Motor setting
![image](https://user-images.githubusercontent.com/53663633/77802548-541eb700-7038-11ea-98be-7aaae834f96f.png)

**Comment by Vrossi050** [comment]
Yes

**Comment by Vrossi050** [comment]
Actually no on the Servo driver. If I put it to 1000 then it alarms

**Comment by Vrossi050** [comment]
7 flashes

**Comment by Johnboy251** [comment]
Question. Is the settings on the servo driver downloaded via a link into the firmware of the driver or are there dip switched to select hybrid servo 1000 P/R?
John...

Seem to be making progress 😳🤞

**Comment by JonWoellhaf** [comment]
It alarms – seven flashes – with which parameter set to 1000?

**Comment by Johnboy251** [comment]
Where are the error codes for the servo driver - can you see what seven flashes refer too in the documentation?

Or is it a case where you turn the power off o the servo driver wait 30 second then put power back on to reset the servodriver?

**Comment by JonWoellhaf** [comment]
The KL-5080H has to be programmed via an (ancient) RS-232 port. No dip switches.

**Comment by Johnboy251** [comment]
> I believe we have found the problem. Please set Pulses/Revolution to 1000 and Encoder Resolution to 1000 and retest. From: Vrossi050 Sent: March 27, 2020 14:43 To: clough42/electronic-leadscrew Cc: JonWoellhaf ; Comment Subject: Re: [clough42/electronic-leadscrew] Gear Ratio (#58) — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Yaayh! 👍🎉

**Comment by Vrossi050** [comment]
The highlighted parameter when set to 1000 will send it into alarm
![image](https://user-images.githubusercontent.com/53663633/77803915-8aaa0100-703b-11ea-83c3-0da1244922f9.png)

**Comment by JonWoellhaf** [comment]
The servo driver manual says 7 flashes indicate Position Following Error.

**Comment by JonWoellhaf** [comment]
OK.

What were the settings when you got one spindle revolution for one leadscrew revolution?

**Comment by Johnboy251** [comment]
Did the motor fail to keep up with the headstock encoder or is it an error trying to drive thservo too fast?

**Comment by Vrossi050** [comment]
lA 
ELS =
3 Micro steps
1000 P/R

Servo driver
current setting:
it takes two Revolutions of the chuck = 1 leadscrew rotation
![image](https://user-images.githubusercontent.com/53663633/77804571-238d4c00-703d-11ea-8b19-676e1d58dafa.png)

**Comment by Vrossi050** [comment]
Now it's 4 chuck turn to 1 leadscrew!! what in the world?

**Comment by JonWoellhaf** [comment]
Yes. That is what I would expect with servo controller set to 4000 pulses per revolution.

What were the settings when you got 1 to 1?

**Comment by Vrossi050** [comment]
These are the settings to get 1 to 1 without changing anything on the ELS Microsteps 3 Revs 1000
![image](https://user-images.githubusercontent.com/53663633/77805255-afec3e80-703e-11ea-84a5-86eebc9c3b8a.png)

**Comment by JonWoellhaf** [comment]
OK!

It must be that the motor encoder is sending a quadrature signal to the servo controller. So it’s seeing 4000 pulses per revolution.

This is exactly the situation with the spindle encoder. It has 1024 lines and the quadrature single produces 4096 counts per revolution.

I think the problem is solved!

Now you get to try cutting some threads again. I predict you will be successful.

Keep us informed.

Good luck.

Jan (Yan)

**Comment by Vrossi050** [comment]
![15853482823717135466245599006890](https://user-images.githubusercontent.com/53663633/77805835-1f166280-7040-11ea-97ec-87440cbca8cc.jpg)
Success! Eurika! Thank you for the great help!

**Comment by JonWoellhaf** [comment]
Great news!

It was a fun project and I learned a lot.

Jan (Yan)

**Comment by Johnboy251** [comment]
Well it’s sorted - great effort by all. 👍 I agree Jan - we’ve learnt a lot and exhibited tremendous Patience! LoL. 😂

**Comment by JonWoellhaf** [comment]
This was actually fun. Much better than watching paint dry – or whatever we’re doing for entertainment while confined.

We can all sleep peacefully tonight!

Thanks for the help.

Jan (Yan)

**Comment by Vrossi050** [comment]
Still having gearbox ratio issues. Any help would be greatly appreciated. 
![Screenshot_20200330-152810_Gallery](https://user-images.githubusercontent.com/53663633/77969313-48ccc500-729e-11ea-9f13-e9fbc51b52b4.jpg)

**Comment by Johnboy251** [comment]
What’s happened? It looked like it was working Friday when you were cutting 8TPI. What were the gear box settings then? I’m assuming you had 8TPI selected on the push button selector.
John

**Comment by Vrossi050** [comment]
I went into the shop today happy. I plugged it in and that is what I got. I will check settings again tomorrow.

**Comment by JonWoellhaf** [comment]
I suspect the latest program was not loaded into the LAUNCHXL’s EEROPM. So when you cycled power, you got an old program.

**Comment by Vrossi050** [comment]
Let's hope that is all it takes. Is there a way to read what is currently on the eemprom?

**Comment by JonWoellhaf** [comment]
There is no practical way to read the EEPROM that I know of.

To positively identify the version you have in EEPROM, I suggest you modify the startup messages in Userinterface.cpp.

For example, you could modify startup_message_2 and add startup_message_3 like this:

const MESSAGE STARTUP_MESSAGE_3 =
{
.messageBuffer = { LETTER_M, LETTER_Y, BLANK, LETTER_V, ONE, BLANK, BLANK, BLANK },
.displayTime = UI_REFRESH_RATE_HZ * 1.5
};

const MESSAGE STARTUP_MESSAGE_2 =
{
.messageBuffer = { LETTER_E, LETTER_L, LETTER_S, DASH, ONE | POINT, ONE | POINT, ZERO, TWO },
.displayTime = UI_REFRESH_RATE_HZ * 1.5,
.next = &STARTUP_MESSAGE_3
};

Then, on power up, if you see MY V1 (or whatever your current version is), you’ll know what version is in EEPROM.

**Comment by Johnboy251** [comment]
The only setting on the Grizzly gear box is the one that gives you the 1:1 ratio from from input shaft of the gearbox to the output shaft. There’s no need to change that from then on otherwise I think confusion will set in.
I agree with Jan on the program that was used when things start doing what we expected was running from EEPROM memory which hopefully needs to be re-flashed and tested. Once the unit performs correctly the TI LaunchPad can be download the retested as a stand alone system confirmed by a hard power reset.
Fingers crossed as Jan says let’s hop that’s what the problem was.
Good luck - stay well & away from the virus.
John
P.S. let us know how you get on.

**Comment by JonWoellhaf** [comment]
I’m a bit confused.

Is the 8 TPI correct?

Is the 12 TPI correct?

Why did you change to IB? All threading and feeds should be done with the gear box set on IA

**Comment by Johnboy251** [comment]
I agree with Jan. 👍

**Comment by Vrossi050** [comment]
Today started with this error. I updated. Still same issue. I don't know my way around code Composer or claim to be a programmer of any sort. I can't seem to get the whole project loaded to the left side so it flashes the entire program. It did erase flash once and I guess it uploaded maybe a partial or whole program. I also wanted to check the servo driver settings and ended up breaking the d9 ground pin on the connector. So that is where I am. In a jam. 
 ![20200331_152122](https://user-images.githubusercontent.com/53663633/78085298-6ae24800-736f-11ea-9c72-be8922322e5f.jpg)

**Comment by JonWoellhaf** [comment]
Sorry for the new problems. Be confident that we will eventually sort it all out.

I had a new thought: perhaps the servo controller change you made was not saved, so it was lost when you powered off. Similar to the problem with the changes to Clough’s software not being loaded into the TI board’s EEPROM.

**Comment by Vrossi050** [comment]
Yes I agree with the servo motor settings not being saved. Using my homemade RS 232 to Rj45 got me into a corner. New cable should be here soon.
Thanks again!

**Comment by Vrossi050** [comment]
I got the new cable and with some effort the settings are saved to the servo drive and motor. 
It working !! Thanks again for your patience and help on this!

**Comment by JonWoellhaf** [comment]
Great news!

**Comment by Johnboy251** [comment]
Brilliant. Good fix, well done. 👍
