### ISSUE TITLE
Use standard metric unit

### ISSUE THREAD

**Issue by OJFord** [clough42/electronic-leadscrew#59]
Thanks for your video series, I stumbled across one yesterday evening and have been binge-watching from the beginning since..!

A minor suggestion though, that might avoid some confusion for metric users, rather than using 'made-up unit' hundredths of a millimetre 'hmm', `1.5mm = 150hmm`, you could instead use the SI unit of micrometres (aka microns) 'μm' (or 'um'), `1.5mm = 1500μm`.

Thanks again, really enjoying the videos, just thought that might be a slight usability improvement for some people that maybe you weren't aware of/didn't think of being used to working in Imperial and more explicit fractions. Cheers.

(PS: I don't even have a lathe, but I'm still enjoying the idea of making an electronic leadscrew for one 😄. Maybe future series will teach me to build the rest of the machine? 😉)

**Comment by clough42** [comment]
Yeah.  The purpose of that unit is to be able to use whole numbers for the math.  Introducing decimals causes a bunch of new complexity in the code.

If/'when I get around to making it configurable on the control panel, I'll format it as a decimal.
