### ISSUE TITLE
Feature request / question: Depth stop

### ISSUE THREAD

**Issue by jchurc16** [clough42/electronic-leadscrew#73]
Hey,

I've been following this project and have a question regarding a depth stop feature. So I'm thinking, the controller knows how many steps it takes to move the leadscrew through 1 revolution, therefore knows how far the carriage moves based on that. Is it possible to have a mode which is decoupled from the spindle rpm and purely deals with depth calculations? I'm thinking this would be handy for facing to a shoulder, internal boring, drilling and possibly threading if this can be tied to spindle rpm too.

I've not seen any discussion on this and would be interested to know if this could be a feature, though with the hardware as it is I'm not sure if this could be added.

**Comment by gusosborne** [comment]
Check out this thread:

https://github.com/clough42/electronic-leadscrew/issues/10

**Comment by jchurc16** [comment]
Thanks, I hadn't considered the disengagement of the leadscrew, I will follow that thread in case of any updates.
