### ISSUE TITLE
servo does not spin and no readout on cotrol panel for rpms.

### ISSUE THREAD

**Issue by tombmatt** [clough42/electronic-leadscrew#78]
the control panel boots up properly, set jumpers and wired according to schematics, left sheild from encoder not connected used common (blue) and vcc (brown) black=A white=B and orange=Z, for testing have 24v dc power (on bench)apply pwr to boards and control boots properly apply 24vdc to motor controler , spin encoder and get nothing. have triple checked wiring everything is by schematic, what should i check.

**Comment by JonWoellhaf** [comment]
I suggest you start by disconnecting the motor controller.

Just so I understand:

When you apply 5 volts to Clough's boost board the display lights and goes through its greeting, "CLOUGH42" then "ELS-1.1.0". Correct?

Does the display then show blank, blank, blank, 0 (in the left-hand four seven-segment displays) and blank with decimal, 005 in the right-hand four displays?

**Comment by tombmatt** [comment]
Yes and yes, that is what the display reads.

Sent from Mail for Windows 10

**Comment by JonWoellhaf** [comment]
Do you have an oscilloscope?

**Comment by tombmatt** [comment]
No. if I bought one of the small inexpensive ones would that work?

Sent from Mail for Windows 10

**Comment by JonWoellhaf** [comment]
I think a small inexpensive scope will work. Please let me know which one you're looking at.
I'd like you to check for pulses on 1A and 1B, (on J12 of the TI board) when you rotate the encoder by hand.
I can see easily see the pulses on 1A and 1B with my scope bandwidth limited to 20 MHz.
The pulses on 1I (digit one, letter India) are harder to see and require triggering on the signal. But I believe 1I is unused for the ELS. Someone please correct me if I'm wrong about this.

**Comment by tombmatt** [comment]
I ordered the scope and probe below
https://www.amazon.com/gp/product/B01ABWNUZS/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1
https://www.amazon.com/gp/product/B0852Y2TY1/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1

Sent from Mail for Windows 10

**Comment by tombmatt** [comment]
I have been reading the other issues and have discoverd that i received from Auto tech the same servo and driver that Scubamachi  received. and i bought it in january like he did. they must have been looking to clear old inventory the picture from Amazon showed the KL-5080H but that isnt what i received. would still like to see why it isnt turning but will have to purchase the correct one eventually.

**Comment by Scubamachi** [comment]
tombmatt,
The motor and controller I purchased did in fact work, but not accurately based on the 1.2 step angle and not the 1.8 angle. I have since started installing them on a power feed for a vertical mill.  You are in good hands with Jon helping out. I'm more than willing to share any info I have. Good luck

**Comment by tombmatt** [comment]
Scubamachi
Thank you for your reply. I knew yours was running just that the 1.2 degrees of rotation made it unworkable for Clough42’s project. I just want to find out why mine wont spin at all. Will eventually buy the proper controller motor.

Sent from Mail for Windows 10

**Comment by Scubamachi** [comment]
![Screenshot_20200811-113245_Amazon Shopping](https://user-images.githubusercontent.com/44989802/89917159-79b2f400-dbc6-11ea-9a27-f347d2eda777.jpg)

**Comment by Scubamachi** [comment]
I purchased this one off Amazon for the ELS project, and I am happy with it.

**Comment by tombmatt** [comment]
I received the scope but only have alligator clip lead. the other one would not connect didn't have bnc

**Comment by JonWoellhaf** [comment]
Are you able to see the test signal on the scope?

The alligator clip should work fine. Connect black to one (or both) of the terminals labeled GND on JP7 on the TI board.

With the encoder connected, put a short piece of thin wire in the red clip and probe 1A and 1B.

May need a helper to spin the encoder.

**Comment by tombmatt** [comment]
Yes got test signal
Here are pics of 1A and 1B;




Don’t know why 1B wave is higher than 1A same settings on scope.


Cat5 used as wire from daughter board to driver orange is + orange white -blue + blue white – green + green white -  on driver orange is pul+
Orange white is pul_  pul + is jumpered to the other +connectios blue is dir- blue white is en- and green white is al+ green is al-



Sent from Mail for Windows 10

**Comment by JonWoellhaf** [comment]
Thomas,
For some reason the waveform images are missing from the email and from GitHub. Please repost.
The wiring is for the servo controller, right?
Please show the wiring for the encoder.
I suggest you unplug the servo controller from the boost board's J2 while we're troubleshooting.
Jan (Yan)

**Comment by tombmatt** [comment]
1B


1A


Sent from Mail for Windows 10

**Comment by JonWoellhaf** [comment]
Bummer! Still no images here (GitHub) nor in the email. Is the problem on my end? Do you see images?

**Comment by tombmatt** [comment]
No my end images were too large trying again
1A

1B

Control panel


Power for motor is not plugged in

Sent from Mail for Windows 10

**Comment by JonWoellhaf** [comment]
Still no joy.

**Comment by tombmatt** [comment]
i will try here
1A
![20200813_133744](https://user-images.githubusercontent.com/11861713/90193174-0a85fd00-dd8a-11ea-8ecb-ac4914f6ad62.jpg)
1B
![20200813_133602](https://user-images.githubusercontent.com/11861713/90193206-1a9ddc80-dd8a-11ea-8b1a-89c7b0df5a6f.jpg)
control panel
![20200811_193810](https://user-images.githubusercontent.com/11861713/90193284-399c6e80-dd8a-11ea-973b-17e30c8fdb39.jpg)

**Comment by tombmatt** [comment]
Put them on GitHub page


Sent from Mail for Windows 10

**Comment by JonWoellhaf** [comment]
Success! I can finally see the images. I like that little scope!

The signal on 1B is very likely the problem. 1A and 1B should be the same. (Actually their phase is different, but that's unimportant now.)

Please unplug the servo driver connector at J2 on Clough's boost board.

Please show me how you've wired the encoder to J12 on the TI board.

**Comment by tombmatt** [comment]
here are new pics
1B
![20200813_174225](https://user-images.githubusercontent.com/11861713/90194961-04921b00-dd8e-11ea-88b9-5d6eb3a23162.jpg)
1A
![20200813_174316](https://user-images.githubusercontent.com/11861713/90195147-5cc91d00-dd8e-11ea-9462-a513583c0727.jpg)
j12
![20200813_174353](https://user-images.githubusercontent.com/11861713/90195180-69e60c00-dd8e-11ea-87a4-0cb59db68ab8.jpg)

blue grnd brown 5v+ orange white black

**Comment by tombmatt** [comment]
you think the encoder is bad?

**Comment by JonWoellhaf** [comment]
I doubt the encoder is bad.
Please try moving the connector to J13 and see what 1A and 1B look like.

**Comment by JonWoellhaf** [comment]
Correction: See what 2A and 2B look like.

**Comment by tombmatt** [comment]
there is no square wave on the line on either A or B just flat jittery line no effect when encoder is turned.

**Comment by JonWoellhaf** [comment]
Interesting! My waveforms are identical. I can't explain that.
With the encoder unplugged, do you see 5 volts on 1A and 1B?
Do you have an ohm meter? If so, with the encoder connector removed, please measure between blue and black, and blue and white. You should get the same reading.
I'll be back in a couple hours.

**Comment by tombmatt** [comment]
1A .4 v  and 1B 5.1

Sent from Mail for Windows 10

**Comment by tombmatt** [comment]
Measured 1A and 1Busing ground on jp8 , got .41V on A and 5.1V on B with an Ohm meter. Used meter to read blue and black and blue and white and got the same readings.

Sent from Mail for Windows 10

**Comment by JonWoellhaf** [comment]
OK. I think we are zeroing in on the problem.
Just to confirm: With the encoder DISCONNECTED, you measure 0.41 volts on 1A and 5.1 volts on 1B?
It looks like the signal on 1B is bad in the first set of photos, but 1A is bad in the second set. Could you have misidentified the photos?
Based on the voltage measurements, 1A should be bad.

**Comment by tombmatt** [comment]
yes i could have crossed them

**Comment by JonWoellhaf** [comment]
OK. Like I've been fond of saying for decades, "the time spent double-checking is never wasted." :)
Please confirm that with the encoder disconnected, you read 0.41 volts on 1A and 5.1 volts on 1B.

**Comment by tombmatt** [comment]
okay retook pictures
1A
![1A](https://user-images.githubusercontent.com/11861713/90214508-50f54f00-ddbe-11ea-9533-79a279917bee.jpg)
1B
![1B](https://user-images.githubusercontent.com/11861713/90214523-5e123e00-ddbe-11ea-9bdd-cf9c789276bd.jpg)

**Comment by tombmatt** [comment]
yes the encoder dis connected 1a is .4 and 1B is 5.1

**Comment by JonWoellhaf** [comment]
OK.
We have positively confirmed that the 1A input on the TI board is bad.
This likely has nothing to do with the encoder.
Is it possible that you inadvertently connected 24 volts to that input?

Anyway, the TI board has a second encoder input, so let's see if we can get that one working.
To confirm once again, with nothing connected to J13, what voltage do you read on 2A and 2B?

**Comment by JonWoellhaf** [comment]
Please look at the jumpers in the lower left of the TI board, the ones below the red LED.
In your photo, it appears that the bottom jumper is connected.
That's JP2, and it must be disconnected.
Please confirm.
Note the jumpers are (confusingly) labeled JP1, JP3, and JP2, top to bottom.
I have all three of mine disconnected.

**Comment by tombmatt** [comment]
2a 1.36  2b .48

Sent from Mail for Windows 10

**Comment by tombmatt** [comment]
All 3 jumpers are off 

Sent from Mail for Windows 10

**Comment by tombmatt** [comment]
![jp2](https://user-images.githubusercontent.com/11861713/90215685-007ff080-ddc2-11ea-8917-c1476de97870.jpg)
all disconnedted

**Comment by JonWoellhaf** [comment]
Acknowledged, all three jumpers are disconnected.

I just checked the TI board schematic to be sure my memory was correct, and confirmed 1A, 1B, 2A, and 2B all have 1k ohm pullups to +5 volts and 1000pF bypass caps to ground.

To get the voltages you're seeing, something on the TI board has failed. All should read +5 with nothing connected.

Is it possible 24 volts was accidentally applied to them?

I am afraid you need a new TI board.

**Comment by tombmatt** [comment]
i dont think 24v were ever close but i could have touched 3 & 5v pads at same time reading power im kinda shakey

**Comment by tombmatt** [comment]
guess i get a new ti board

**Comment by JonWoellhaf** [comment]
You're very welcome.
Please let us know if a new TI board fixes the problem.
Sorry it wasn't a simple fix.
Anyone else have any thoughts about this?

**Comment by Vrossi050** [comment]
Are both switches set on S3 and S4 on the TI board per the wiki page picture?

**Comment by tombmatt** [comment]
yes

Sent from Mail for Windows 10

**Comment by tombmatt** [comment]
ordered and received new TI panel. programed and installed other bits and It Works. Thank You JonWoellhaf and all others that helped.

**Comment by JonWoellhaf** [comment]
Great news, Thomas!
I hope the rest of the project goes smoothly.

**Comment by clough42** [comment]
Thanks, @JonWoellhaf .  You're a real gem.
