### ISSUE TITLE
quick question

### ISSUE THREAD

**Issue by bacca5419** [clough42/electronic-leadscrew#79]
Hi all from Australia. I am about to start putting the ELS kit together and noticed there are 2 small switches on the side of the servo driver ( KL-5080H ). What position should they be in. Regards Noel.

**Comment by JonWoellhaf** [comment]
Hi, Noel.

My KL-5080H manual PDF from Automation Technology, says this (no page number): "DIP Switch - Motor SEL
It is reserved for future use. Now there is no function for these DIP switch."

Jan (Yan)

**Comment by bacca5419** [comment]
Hi Jan (Yan). Thank you for your reply. That eases my mind. I dont know anything much about electronics. Didnt want to burnt anything out. Regards. Noel.
