### ISSUE TITLE
Spindle to encoder ratio

### ISSUE THREAD

**Issue by egapelr** [clough42/electronic-leadscrew#81]
I am close to installing the Clough42 Electronic Lead Screw to my old Atlas 10F lathe.  I understand that the ELS program is assuming a 1:1 ratio of spindle to encoder.  If I need to modify the timing gears from spindle to the encoder which is generating 4096 pulses per revolution, where in the programming do I change the new ratio?  If for example I have a 60 tooth gear on the spindle feeding a 40 tooth gear on the encoder, in the configuration file do I then simply multiply the 4096 pulses by 60/40 to compensate for the extra speed that the encoder will be turning at?  I think this should work I just want someone to verify my thoughts.  Thanks to all of you and especially to James Clough for his excellent and thorough work.  Much appreciated.  It will bring my 1940's Atlas Lathe to the 21st century.

**Comment by tmetty** [comment]
Did it work? I'm curious.

**Comment by egapelr** [comment]
I originally thought that I might need to place a larger pulley on the spindle thus necessitating something other than a 1:1 ratio.  I have since determined to try a different arrangement a maintain a 1:1 ratio as the coding requires.  So I cannot definitively answer this issue other than to suggest that it probably would work.  No one has offered any possible solutions that would contradict this supposition.  Thanks for your interest.

**Comment by tmetty** [comment]
My encoder arrived today. I’m installing the ELS (thank you, James) on my 25 year old Smithy 1220XL (no giggling), and I installed the hybrid servo with 3:1 reduction. For the encoder, the leadscrew output shaft from the headstock spins a little slower than the spindle but would make for a simple installation. If necessary I can use the original gear train to accomplish 1:1, but where’s the fun in that? Thank you for your reply.

**Comment by Chucksbp** [comment]
egapelr, I have a friend that is in the process of installing the ELS on an Atlas 10F lathe. i was wondering 9f you could so kindly post some pictures of your installation. It would be deeply appreciated. Or email them to me at mayerchak@comcast.net any help would be appreciated. I did one on my Atlas 618 but this 10F is a bit different.
