### ISSUE TITLE
Motor Noise

### ISSUE THREAD

**Issue by chaszz** [clough42/electronic-leadscrew#85]
The hybrid servo that James used looks like a reasonable candidate for my South Bend 1001 (8 x 18). However, my lathe is really quiet and he made a comment in the video about the motor making more noise than expected. Has this been an issue for anyone?   I think listening continually to stepper whine would drive me nuts.

**Comment by petmakris** [comment]
Stepper do make noise. 

This is completely outside of the scope of ELS, but my opinion would be to checkout some stepper motor drivers that feature quiet operation like those based on Trinamic ICs. 

You could checkout various video reviews on stepper motor drivers before getting into.

Independent from the noise, I would choose a closed loop motor and driver.

**Comment by chaszz** [comment]
Thanks. I hadn’t thought of looking for video reviews.

Sent from my iPhone
Charles Walling

On Sep 10, 2020, at 3:30 PM, -Yo Meister <notifications@github.com> wrote:

﻿

Stepper do make noise.

This is completely outside of the scope of ELS, but my opinion would be to checkout some stepper motor drivers that feature quiet operation like those based on Trinamic ICs.

You could checkout various video reviews on stepper motor drivers before getting into.

Independent from the noise, I would choose a closed loop motor and driver.

**Comment by clough42** [comment]
Closing.
